name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.sha }}-tests
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        codeception: ['^4.0', '^5.0']
        deps: ['lowest', 'latest']
        exclude:
          # Codeception 5 requires PHP ≥ 8
          - php: '7.4'
            codeception: '^5.0'
          # PHP >= 8.5 will not run Codeception 4
          - php: '8.5'
            codeception: '^4.0'
            deps: 'lowest'
          # PHP >= 8.5 will not run Codeception 4
          - php: '8.5'
            codeception: '^4.0'
            deps: 'latest'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - run: gem install mime-types --version "< 3"
      - run: gem install --conservative mailcatcher
      - run: mailcatcher
      # Temporary workaround for https://github.com/sj26/mailcatcher/issues/182
      - run: mailcatcher -f > out.txt&
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          ini-values: "sendmail_path = /usr/bin/env catchmail -f some@from.address"
          php-version: ${{ matrix.php }}
      - uses: ramsey/composer-install@v3
        env:
          COMPOSER_POLICY_ADVISORIES_BLOCK: 0
        with:
          dependency-versions: ${{ matrix.deps }}
          composer-options: "--with=codeception/codeception:${{ matrix.codeception }} ${{ case(matrix.php == '8.5', '--with codeception/codeception:>=5.3.4', '') }} ${{ case(matrix.codeception == '^4.0', '--with=behat/gherkin:<4.13', '') }} ${{ case(matrix.php == '7.4', '', '--with=symfony/yaml:>=2.8.0') }}"
      - run: php vendor/bin/codecept build
      - name: Acceptance tests
        run: php vendor/bin/codecept run acceptance -d
      - name: Unit tests
        env:
          XDEBUG_MODE: coverage
        run: php vendor/bin/codecept run unit --coverage-xml -d
